title: Janith Karunarathna
logo: /assets/img/profilepic_modified.png
description:  Postgraduate Diploma in AI | BSc (Hons) in Aeronautical Engineering
show_downloads: true
theme: jekyll-theme-minimal
